<div class="wrap wp_dummy_content_generator-dashboard">
	<div class="wp_dummy_content_generator-header">
		<h1>WP Dummy Content Generator <?=wp_dummy_content_generator_PLUGIN_NAME_VERSION?></h1>
		<div class="wp_dummy_content_generator-description">
			Thank you for choosing WP Dummy Content Generator! We hope that your experience with our plugin makes creating <b>Dummy users, Dummy posts & custom posts, Dummy woocommerce products</b> quick and easy.
		</div>
	</div>

	<div class="wp_dummy_content_generator-features-section">
		<h2>What our plugin provides</h2>
		<div class="wp_dummy_content_generator-feature-grid">
			<div class="wp_dummy_content_generator-feature-card">
				<div class="feature-card-icon">
					<span class="dashicons dashicons-admin-users"></span>
				</div>
				<div class="feature-card-heading">Dummy Users</div>
				<div class="feature-card-content">
					<p>As the name, "Dummy users" sounds like something illegal but actually its not. The main purpose of generating Dummy users is to check the functionality which is related to multiple users.</p>
					<div class="feature-card-action">
						<a href="?page=wp_dummy_content_generator-users" class="button button-primary">Generate Users</a>
					</div>
				</div>
			</div>
			<div class="wp_dummy_content_generator-feature-card">
				<div class="feature-card-icon">
					<span class="dashicons dashicons-admin-post"></span>
				</div>
				<div class="feature-card-heading">Dummy Posts/Custom Posts</div>
				<div class="feature-card-content">
					<p>You can generate Dummy WordPress posts and custom posts. The purpose is again the same that it is for checking functionality like load more posts or filters etc.</p>
					<div class="feature-card-action">
						<a href="?page=wp_dummy_content_generator-posts" class="button button-primary">Generate Posts</a>
					</div>
				</div>
			</div>
			<div class="wp_dummy_content_generator-feature-card">
				<div class="feature-card-icon">
					<span class="dashicons dashicons-cart"></span>
				</div>
				<div class="feature-card-heading">Woocommerce Products</div>
				<div class="feature-card-content">
					<p>Woocommerce products are very important for e-commerce theme development. You can generate n number of woocommerce products using this plugin.</p>
					<div class="feature-card-action">
						<a href="?page=wp_dummy_content_generator-products" class="button button-primary">Generate Products</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="wp_dummy_content_generator-info-card">
		<div class="info-card-content">
			<h2>Worried about deleting data generated by WP Dummy Content Generator plugin?</h2>
			<p>Rest assured, the process of deleting the dummy data generated by our plugin is designed to be safe, reliable, and hassle-free. You can confidently remove all the generated content with ease and peace of mind. Our plugin ensures that the deletion process is handled smoothly, allowing you to maintain a clean and streamlined website whenever needed.</p>
			<p class="info-highlight">
				<b>Enjoy the features of WP Dummy Content Generator!</b>
			</p>
		</div>
	</div>
</div>